environment:
  global:
    PYTHON: "C:\\Python36"

install:
  - pip install git+https://github.com/astrofrog/autowheel.git

build_script:
  - mkdir wheelhouse
  - autowheel windows32 --output-dir=wheelhouse
  - autowheel windows64 --output-dir=wheelhouse
  - dir wheelhouse
  - 7z a wheels_windows.zip wheelhouse

artifacts:
  - path: "wheels_windows.zip"
    name: Wheels
