install:
  - pip install git+https://github.com/astrofrog/autowheel.git

build_script:
  - mkdir wheelhouse
  - autowheel windows32 --output-dir=wheelhouse --ignore-existing
  - autowheel windows64 --output-dir=wheelhouse --ignore-existing
  - dir wheelhouse

artifacts:
  - path: "wheelhouse\\*.whl"
    name: Wheels
