jobs:

- job: Python
  pool:
    vmImage: vs2017-win2016
  strategy:
    matrix:
      27_32:
        python: '2.7'
        arch: 'x86'
      27_64:
        python: '2.7'
        arch: 'x64'
      34_32:
        python: '3.4'
        arch: 'x86'
      34_64:
        python: '3.4'
        arch: 'x64'
      35_32:
        python: '3.5'
        arch: 'x86'
      35_64:
        python: '3.5'
        arch: 'x64'
      36_32:
        python: '3.6'
        arch: 'x86'
      36_64:
        python: '3.6'
        arch: 'x64'
      37_32:
        python: '3.7'
        arch: 'x86'
      37_64:
        python: '3.7'
        arch: 'x64'

  steps:

  - task: UsePythonVersion@0
    inputs:
      versionSpec: $(python)
      architecture: $(arch)

  - script: "pip install numpy --no-binary :all:"
    displayName: Installing numpy
