jobs:
- job: ${{ format(parameters.name) }}
  pool:
    ${{ if eq(parameters.os, 'macosx') }}:
      vmImage: macOS 10.13
    ${{ if eq(parameters.os, 'linux32') }}:
      vmImage: Ubuntu 16.04
    ${{ if eq(parameters.os, 'linux64') }}:
      vmImage: Ubuntu 16.04
    ${{ if eq(parameters.os, 'windows32') }}:
      vmImage: vs2017-win2016
    ${{ if eq(parameters.os, 'windows64') }}:
      vmImage: vs2017-win2016

  steps:

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '2.7'
      architecture: 'x86'

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '2.7'
      architecture: 'x64'

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.4'
      architecture: 'x86'

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.4'
      architecture: 'x64'

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.5'
      architecture: 'x86'

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.5'
      architecture: 'x64'

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      architecture: 'x86'

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      architecture: 'x64'

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
      architecture: 'x86'

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
      architecture: 'x64'

  - script: pip install git+https://github.com/astrofrog/cibuildwheel.git@azure-windows
    displayName: Installing cibuildwheel

  - script: pip install git+https://github.com/astrofrog/autowheel.git
    displayName: Installing autowheel

  - script: mkdir wheelhouse
    displayName: Making wheelhouse directory

  - script: autowheel ${{ parameters.os }} --output-dir=wheelhouse --build-existing
    displayName: Running autowheel
    ${{ if eq(parameters.os, 'macosx') }}:
      env:
        CC: clang

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: wheelhouse
      includeRootFolder: true
      archiveType: 'tar'
      tarCompression: 'gz'
      archiveFile: '$(Build.ArtifactStagingDirectory)/wheels_${{ parameters.os }}.tar.gz'

  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: wheels-${{ parameters.os }}
      targetPath: $(Build.ArtifactStagingDirectory)
