jobs:

- template: azure-template.yml
  parameters:
    name: Linux
    os: linux32

- template: azure-template.yml
  parameters:
    name: Linux
    os: linux64

- template: azure-template.yml
  parameters:
    name: MacOSX
    os: macosx

# FIXME: cibuildwheel doesn't work on Azure yet, see appveyor.yml
# - template: azure-template.yml
#   parameters:
#     name: Windows
#     os: windows
